import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import ts from 'typescript';
const source=await readFile(new URL('../src/features/practice/lib/speechsuper.ts',import.meta.url),'utf8');
const js=ts.transpileModule(source,{compilerOptions:{target:ts.ScriptTarget.ES2023,module:ts.ModuleKind.ESNext}}).outputText.replace("'./assessmentRequest'",JSON.stringify(new URL('../src/features/practice/lib/assessmentRequest.ts',import.meta.url).href));
const {assessSpeech,toWav}=await import('data:text/javascript;base64,'+Buffer.from(js).toString('base64'));
let closes=0;
globalThis.AudioContext=class {async decodeAudioData(){return {duration:1};}close(){closes++;return new Promise(()=>{});}};
globalThis.OfflineAudioContext=class {destination={};createBufferSource(){return {connect(){},start(){}};}async startRendering(){return {getChannelData:()=>new Float32Array(16000).fill(.1)};}};
const blob=new Blob(['synthetic']);
const wav=await toWav(blob);assert.equal(wav.size,32044);assert.equal(closes,1);
let requests=0;
globalThis.fetch=async()=>{requests++;return new Response(JSON.stringify({detail:'SpeechSuper 响应超时，请稍后重试。'}),{status:504});};
await assert.rejects(assessSpeech('word','brown',blob),/SpeechSuper 响应超时/);
globalThis.fetch=async()=>new Response('<html>Bad gateway</html>',{status:502});
await assert.rejects(assessSpeech('word','brown',blob),/返回异常/);
const controller=new AbortController();
globalThis.fetch=async()=>({json:()=>new Promise(()=>{})});
const stalled=assessSpeech('word','brown',blob,'speechsuper',{signal:controller.signal});
setTimeout(()=>controller.abort(new Error('test deadline')),10);
await assert.rejects(stalled,/test deadline/);
globalThis.fetch=async(_url,init)=>{requests++;const body=JSON.parse(init.body);assert.deepEqual(Object.keys(body),['kind','text','audio']);return Response.json({kind:'word',text:'brown',result:{pronunciation:85}});};
assert.equal((await assessSpeech('word','brown',blob)).result.pronunciation,85);
const before=requests;
globalThis.AudioContext=class{async decodeAudioData(){throw new DOMException('decode failed','EncodingError');}async close(){}};
await assert.rejects(assessSpeech('word','brown',blob),/无法读取这段录音/);assert.equal(requests,before);
console.log('PASS: WAV conversion, nonblocking close, HTTP 504, invalid 502 body, stalled response deadline, unchanged payload, successful retry, invalid audio');
