BEGIN;
CREATE TABLE ft_training.content_versions(version text PRIMARY KEY, source_description text NOT NULL, source_sha256 text NOT NULL, created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE ft_training.speech_questions(content_version text NOT NULL REFERENCES ft_training.content_versions(version), id text NOT NULL, kind text NOT NULL CHECK(kind IN ('word','sentence')), text text NOT NULL, metadata jsonb NOT NULL, PRIMARY KEY(content_version,id));
CREATE TABLE ft_training.assessment_rules(content_version text NOT NULL REFERENCES ft_training.content_versions(version), stage text NOT NULL CHECK(stage IN ('word','sentence','grammar')), question_count integer NOT NULL CHECK(question_count>0), pass_percent integer NOT NULL CHECK(pass_percent BETWEEN 0 AND 100), settings jsonb NOT NULL, description_zh text NOT NULL, PRIMARY KEY(content_version,stage));
COMMENT ON TABLE ft_training.speech_questions IS '第一关单词与第二关句子题库；按版本保存';
COMMENT ON TABLE ft_training.grammar_questions IS '第三关语法题、两个选项、正确选项与原始解析';
COMMENT ON TABLE ft_training.assessment_rules IS '三关抽题、评分、通过、解锁与重考规则；保存配置不等于应用已接入';
INSERT INTO ft_training.content_versions VALUES('ft-target-words-v2-round-v1-grammar-20260920','FT Target Words V2.xlsx + FT Questions.xlsx；当前项目题库快照','25efd6dcc8f6e19c85e5e2018e3e1046b89fe7a75ec7f5ff94c36d6db1c5e698',now());
INSERT INTO ft_training.speech_questions VALUES
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-yellow','word','yellow','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-brown','word','brown','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-green','word','green','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-blue','word','blue','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-ant','word','ant','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-apple','word','apple','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-bird','word','bird','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-box','word','box','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-candy','word','candy','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-cat','word','cat','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-happy','word','happy','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-sad','word','sad','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-angry','word','angry','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-silly','word','silly','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-red','word','red','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-bear','word','bear','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-car','word','car','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-monster','word','monster','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-arrow','word','arrow','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-antelope','word','antelope','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-bread','word','bread','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-football','word','football','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-camel','word','camel','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-cucumber','word','cucumber','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-elephants','word','elephants','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-hamsters','word','hamsters','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-zebras','word','zebras','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-shorts','word','shorts','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-sneakers','word','sneakers','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-pants','word','pants','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-boots','word','boots','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-bears','word','bears','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-panda','word','panda','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-pandas','word','pandas','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-cheetah','word','cheetah','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-cheetahs','word','cheetahs','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-kangaroo','word','kangaroo','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-kangaroos','word','kangaroos','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-circle','word','circle','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-triangle','word','triangle','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-word-square','word','square','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-f815800771b8','sentence','It''s a yellow cake.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-8f3f08bcd30a','sentence','It''s a brown cake.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-32e49860cf71','sentence','It''s a green cake.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-17e7799bdc74','sentence','It''s a blue cake.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-e6a0d0eda900','sentence','I feel happy.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-3fc8c65caddf','sentence','I feel sad.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-aa45f011598c','sentence','I feel angry.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-f71a6440bd61','sentence','I feel silly.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-522e4450748f','sentence','I like red cherries.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-79a5b67e60ad','sentence','I like yellow mangoes.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-39c51518fb52','sentence','I like green kiwis.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-a3d89d78e833','sentence','It''s red.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-b10126768ee6','sentence','It''s yellow.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-1e695bb7dc6a','sentence','It''s blue.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-0bc71291eb6f','sentence','It''s a brown bear.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-bc5ab996cf15','sentence','It''s a brown monster.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-dc4470728547','sentence','It''s a yellow bear.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-ccb9c7be7688','sentence','It''s a yellow car.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-fd3bae219e40','sentence','It''s a green car.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-9a7503dd0aa7','sentence','I like the brown bear.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-472c1255b1cd','sentence','I like the yellow bear.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-d3dfeb523221','sentence','I like the yellow car.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-a9397a3b5f64','sentence','I like the green car.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-5b076c91c986','sentence','I like the green monster.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-95510ba6b780','sentence','I like the brown monster.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-f7f1e7495105','sentence','I see elephants. They''re big and strong.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-2ed61ab00507','sentence','I see hamsters. They''re small and cute.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-bfb9deea4cd4','sentence','I see zebras. They''re black and white.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-19824d98e613','sentence','I will play the guitar.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-f526d658c219','sentence','I will go swimming.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-d15e60c3590c','sentence','I will play basketball.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-5730fbdef633','sentence','I will go to a dance class.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-52a27fdcebaf','sentence','I will read a book.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-df20793d8e3f','sentence','I will go to an art class.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-3d3db9cb7e04','sentence','I''m wearing a shirt.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-60d3097274ba','sentence','I''m wearing shorts.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-e4149cf61ce8','sentence','I''m wearing sneakers.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-05504fe3a402','sentence','I''m wearing a coat.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-ec57f5509ce6','sentence','I''m wearing pants.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-6439421a46b4','sentence','I''m wearing boots.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-bd7225d54955','sentence','He is wearing a shirt, shorts and sneakers.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-38ee96db45fb','sentence','I like bears.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-9843d164f918','sentence','I like pandas.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-4a36d61944a9','sentence','I like cheetahs.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-a225f4964be1','sentence','I like kangaroos.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-a23544c9c28c','sentence','Let''s try bumper cars.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-21dd9d0b218b','sentence','Let''s try rock climbing.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-3a2fda94b064','sentence','Let''s try the trampoline.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-504400974f6f','sentence','I see a circle.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-dc08560837b9','sentence','I see a triangle.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-d2c78cb03a2f','sentence','I see a square.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-cabd62dc81c5','sentence','I want to go skiing.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-c2fcc9169f72','sentence','I want to go cycling.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-39f76d675d16','sentence','I want to go swimming.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-91c7d3be27f9','sentence','I want to go camping.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-7f66eeaf86b6','sentence','I''m making coffee.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-b6d8c5c92b17','sentence','I''m having a barbeque.','{"ipa":"","zh":"","hint":"","example":""}'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-sentence-ce901d25619f','sentence','I''m playing soccer.','{"ipa":"","zh":"","hint":"","example":""}');
INSERT INTO ft_training.grammar_questions VALUES
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-01','What color is it?','It''s a yellow.','It''s yellow.','1','“Yellow” is a color adjective, so we don''t use “a” before it when simply describing the color.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-02','Which one is correct?','Do you know what is his hobby?','Do you know what his hobby is?','1','In an indirect question, the word order changes to subject + verb: “what his hobby is,” not “what is his hobby.”'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-03','THe sentence pattern is "These are sneakers." What is the correct question to ask?','What are these?','What''s this?','0','Because “these” is plural, we use “are.” The question follows the pattern What + are + these?'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-04','She (like, likes) playing basketball.','like','likes','1','Use “likes” because “she” is a singular subject. In the simple present tense, the verb takes -s with he/she/it.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-05','Which sentence is correct?','She go to school yesterday.','She went to school yesterday.','1','“Yesterday” shows that the action happened in the past, so we use the past tense “went,” not “go.”'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-06','What''s this?','It''s a bumper cars.','It''s a bumper car.','1','Use “a bumper car” because the question asks about one thing: “What’s this?”'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-07','Is this a bumper cars?','Yes, these are bumper cars','Yes, this is bumper cars','0','Yes, these are bumper cars target word is in plural form'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-08','Do you like bumpers cars?','Yes, I do','Yes, I like','0','Yes, I do-is grammatically correct as a direct short answer and It starts with the auxiliary verb “Do.”'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-09','Did you play here at the Play Zone?','Yes, I do','Yes, I did.','1','The question starts with “Did”, so the short answer should use “did.”'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-10','Are these red tomatoes and bell peppers?','Yes, these are red tomatoes and bell peppers','Yes, It is red tomatoes and bell peppers','0','These are a red tomatoes and bell peppers-subject are in both in plural form'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-11','Which one is correct?','What can a bird do?','What bird can do?','0','What can a bird do? → A bird can fly.
“Can” comes before the subject when asking about ability.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-12','Which one is correct?','What''s this? (bumper cars)','What are thse?(bumper cars)','1','Bunper cars-target word is in plural form'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-13','Which one is correct?','teacher will give you a fries.','teacher will give you some fries','1','“A fries” is incorrect. Fries is plural, so we cannot use “a” before it.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-14','What is it?','It''s a beef.','It''s beef.','1','It’s a beef. — generally incorrect when identifying the type of meat.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-15','Which one is correct?','What are the advices that the dietitian gave?”','What pieces of advice did the dietitian give?','1','Advice is an uncountable noun in English. We do not normally make it plural as “advices.”'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-16','Which one is correct?','Do you like playing the trampoline?','Do you like playing on the trampoline?','1','We use “on” because a trampoline is a surface that you jump/play on.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-17','Which one is correct?','What can a bird do?','What does a bird can do?','0','Can is already a helping/modal verb, so we don''t use does with it.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-18','Do you have a yellow bear?','Yes, I do.','Yes, I have.','0','The question starts with “Do you have…?”, so we use do in the short answer.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-19','What made this sentence wrong? "Practice with an English teachers everyday."','an English teacher','English teachers','0','“An” is used only with a singular countable noun. Since “teachers” is plural, we should say “English teachers.”'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-20','Which question is correct?','What a bird can do?','What can a bird do?','1','For a WH-question, we usually put the helping/modal verb before the subject.

What + can + subject + verb?'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-21','Which of these sentences is correct?
','She need to answer in a complete sentences.','She needs to answer in a complete sentence.','1','With she/he/it, the verb takes -s: "A” is singular, so sentence should not be plural.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-22','Which question is correct?','Is junkfoods healthy or unhealthy?','Is junk food healthy or unhealthy?','1','“junk food” is usually treated as an uncountable noun, so we don''t normally add -s.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-23','Which question is correct?','Does she like doing yoga?','Does she likes doing yoga?','0','When we use “does,” the main verb stays in its base form.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-24','Which question is correct?','Why does he like playing soccer?','Why does he likes playing soccer?','0','After “does,” use the base form of the verb.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-25','Which question is correct?','Whose feet are bigger?','Whose feet is bigger?','0','Feet is the plural form of foot, so we use are, not is.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-26','Which question is correct?','Who likes watching movies in your family?','Who like watching movies in your family?','0','who refers to one person in the family, so we use likes.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-27','Which question is correct?','What color are your shorts?','What color is your shorts?','0','Shorts is a plural noun, so we use are, not is.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-28','How many pairs of sneakers do you have?','I have three pairs of sneakers.','I have a three pairs of sneakers.','0','We do not use “a” before a plural number.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-29','What is she wearing?','She’s wearing a sweater, a skirt, and boots.','She’s wearing a sweater, a skirt, and a boots.','0','Boots is a plural noun, so we don''t use “a” before it.'),
('ft-target-words-v2-round-v1-grammar-20260920','ft-grammar-20260920-30','What is he doing?','He plays guitar.','He is playing the guitar.','1','he question “What is he doing?” asks about an action happening now.');
INSERT INTO ft_training.assessment_rules VALUES
('ft-target-words-v2-round-v1-grammar-20260920','word','30','80','{"score_formula":"pronunciation","rounding_decimal_places":1,"all_items_must_pass":true,"retry_failed_item":true,"prerequisite":null}','第一关：随机抽30个单词；发音分四舍五入到1位小数，每题至少80分，全部通过后解锁第二关。'),
('ft-target-words-v2-round-v1-grammar-20260920','sentence','20','80','{"score_formula":"(pronunciation*0.85+fluency*0.10+rhythm*0.05)*integrity/100","rounding_decimal_places":1,"all_items_must_pass":true,"retry_failed_item":true,"prerequisite":"word"}','第二关：随机抽20个句子；（发音×85%＋流利度×10%＋韵律×5%）×完整度/100，四舍五入到1位小数，每题至少80分，全部通过后解锁第三关。'),
('ft-target-words-v2-round-v1-grammar-20260920','grammar','30','80','{"required_correct":24,"max_wrong":6,"fail_on_wrong_number":7,"attempts_per_question":1,"sequential":true,"wrong_answer_reveals_solution":false,"wrong_answer_can_continue":true,"shuffle_on_failed_reentry":true,"resume_unfinished":true,"prerequisite":"sentence"}','第三关：30题，每题只提交一次，按顺序作答，答错标记错误且不揭示答案。完成后至少答对24题通过；累计错7题立即结束，重考打乱顺序。未完成时保留进度。');
INSERT INTO ft_training.schema_versions VALUES(2,now());
COMMIT;
