/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Enrollments */
        get: operations["enrollments_api_v1_enrollments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/{enrollment_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Progress */
        get: operations["progress_api_v1_enrollments__enrollment_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/enrollments/{enrollment_id}/course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Course */
        get: operations["course_api_v1_enrollments__enrollment_id__course_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CourseResponse */
        CourseResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Code */
            code: string;
            /** Title */
            title: string;
            /**
             * Course Version Id
             * Format: uuid
             */
            course_version_id: string;
            /** Version */
            version: string;
            /** Locale */
            locale: string;
            /** Modules */
            modules: components["schemas"]["ModuleEntry"][];
        };
        /** Enrollment */
        Enrollment: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Teacher Id
             * Format: uuid
             */
            teacher_id: string;
            /**
             * Course Version Id
             * Format: uuid
             */
            course_version_id: string;
            /** Run No */
            run_no: number;
            /**
             * Lifecycle State
             * @constant
             */
            lifecycle_state: "active";
        };
        /** Envelope[CourseResponse] */
        Envelope_CourseResponse_: {
            data: components["schemas"]["CourseResponse"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** Envelope[ProgressResponse] */
        Envelope_ProgressResponse_: {
            data: components["schemas"]["ProgressResponse"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** Envelope[Teacher] */
        Envelope_Teacher_: {
            data: components["schemas"]["Teacher"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** Envelope[list[Enrollment]] */
        Envelope_list_Enrollment__: {
            /** Data */
            data: components["schemas"]["Enrollment"][];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** ErrorDetail */
        ErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorDetail"];
            /**
             * Request Id
             * Format: uuid
             */
            request_id: string;
        };
        /** ModuleEntry */
        ModuleEntry: {
            /**
             * Part Key
             * @enum {string}
             */
            part_key: "orientation" | "practice";
            /** Path */
            path: string;
        };
        /** PartProgress */
        PartProgress: {
            /**
             * Part Key
             * @enum {string}
             */
            part_key: "orientation" | "practice";
            /** Can Enter */
            can_enter: boolean;
            /**
             * Completion State
             * @enum {string}
             */
            completion_state: "not_started" | "in_progress" | "completed";
            /**
             * Assessment State
             * @enum {string}
             */
            assessment_state: "not_evaluated" | "passed" | "failed" | "needs_review";
            /** Progress Percent */
            progress_percent?: number | null;
            /** Revision */
            revision: number;
            /** Summary Version */
            summary_version: number;
            /** Summary */
            summary: {
                [key: string]: unknown;
            };
        };
        /** ProgressResponse */
        ProgressResponse: {
            /**
             * Enrollment Id
             * Format: uuid
             */
            enrollment_id: string;
            /**
             * Course Version Id
             * Format: uuid
             */
            course_version_id: string;
            /** Parts */
            parts: components["schemas"]["PartProgress"][];
        };
        /** Teacher */
        Teacher: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** External Teacher Id */
            external_teacher_id: string;
            /** Display Name */
            display_name: string;
            /** Locale */
            locale: string;
            /** Timezone */
            timezone: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_Teacher_"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    enrollments_api_v1_enrollments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_list_Enrollment__"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    progress_api_v1_enrollments__enrollment_id__progress_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_ProgressResponse_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    course_api_v1_enrollments__enrollment_id__course_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                enrollment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope_CourseResponse_"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Method Not Allowed */
            405: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
