import {useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {liveApi,LiveApiError,type Teacher,type Enrollment,type Round,type Stage} from './api';
import {toWav} from '../practice/lib/speechsuper';
import '../login/Login.css';
import './LiveApp.css';
const labels:Record<Stage,string>={word:'单词朗读',sentence:'句子朗读',grammar:'语法考核'};
const stages:Stage[]=['word','sentence','grammar'];
const errorText=(e:unknown)=>e instanceof Error?e.message:'服务暂不可用，请稍后重试。';

function Login({onLogin}:{onLogin:()=>void}) {
 const [email,setEmail]=useState(''),[secret,setSecret]=useState(''),[mode,setMode]=useState<'password'|'email'>('password'),[challenge,setChallenge]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await liveApi(mode==='password'?'/auth/password':'/auth/verify',mode==='password'?{email,password:secret}:{challenge_id:challenge,code:secret});onLogin();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function send(){setBusy(true);setError('');try{const r=await liveApi<{challenge_id:string}>('/auth/email',{email});setChallenge(r.challenge_id);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <div className="ft-login"><header className="fl-header"><a href="/login" className="fl-brand">51Talk<span>FT 教师培训</span></a></header><main className="fl-main"><section className="fl-welcome"><span className="fl-eyebrow">TEACH WITH CONFIDENCE</span><h1>准备好，<br/>迎接你的课堂。</h1><p>从每一次练习开始，<br/>让教学更自信。</p><div className="fl-stages"><span><b>01</b>单词朗读</span><span><b>02</b>句子朗读</span><span><b>03</b>语法测验</span></div></section><section className="fl-card"><h2>登录教师培训</h2><p>使用培训负责人分配的账号。</p><form onSubmit={submit}><label htmlFor="live-email">邮箱</label><input id="live-email" type="email" required autoComplete="username" value={email} onChange={e=>{setEmail(e.target.value);setChallenge('');setSecret('');}}/><label htmlFor="live-secret">{mode==='password'?'密码':'验证码'}</label><input id="live-secret" type={mode==='password'?'password':'text'} autoComplete={mode==='password'?'current-password':'one-time-code'} required value={secret} onChange={e=>setSecret(e.target.value)}/>{mode==='email'&&<button type="button" disabled={busy||!email} onClick={send}>获取验证码</button>}{challenge&&<p role="status">若邮箱已登记，你会收到验证码；5分钟内有效。</p>}{error&&<p role="alert" className="fl-error">{error}</p>}<button className="fl-submit" disabled={busy||(mode==='email'&&!challenge)}>{busy?'处理中…':'登录并开始培训 →'}</button></form><button className="live-link" onClick={()=>{setMode(mode==='password'?'email':'password');setSecret('');setError('');}}>{mode==='password'?'使用邮箱验证码':'使用账号密码'}</button></section></main></div>;
}

function Reading({round,onRefresh,onError}:{round:Round;onRefresh:()=>Promise<void>;onError:(text:string)=>void}){
 const items=round.items||[];
 const first=items.findIndex(q=>q.best_score===null||Number(q.best_score)<80);
 const [selected,setSelected]=useState(first<0?0:first),[blob,setBlob]=useState<Blob|null>(null),[url,setUrl]=useState(''),[recording,setRecording]=useState(false),[busy,setBusy]=useState(false),[result,setResult]=useState('');
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),submission=useRef<string|null>(null);
 const item=items[selected];
 useEffect(()=>{if(!blob){setUrl('');return;}const value=URL.createObjectURL(blob);setUrl(value);return()=>URL.revokeObjectURL(value);},[blob]);
 useEffect(()=>()=>{if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(track=>track.stop());},[]);
 async function start(){onError('');try{const media=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=media;const value=new MediaRecorder(media);recorder.current=value;const chunks:Blob[]=[];value.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};value.onstop=()=>{setBlob(new Blob(chunks,{type:value.mimeType}));submission.current=null;setRecording(false);media.getTracks().forEach(t=>t.stop());};value.start();setRecording(true);setResult('');timer.current=setTimeout(()=>{if(value.state==='recording')value.stop();},round.stage==='word'?20000:90000);}catch(e){onError(errorText(e));}}
 async function upload(){if(!blob||!item)return;setBusy(true);onError('');try{const wav=await toWav(blob);const bytes=new Uint8Array(await wav.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));submission.current??=crypto.randomUUID();const data=await liveApi<{status:string;score:number|null;error_code?:string}>(`/speech/rounds/${round.id}/assessments`,{question_id:item.id,client_submission_id:submission.current,audio:btoa(binary),active_duration_ms:Math.round((wav.size-44)/32)});if(data.status==='scored'){setResult(`本次得分 ${data.score} / 100 · ${Number(data.score)>=80?'已通过':'请重新练习'}`);submission.current=null;await onRefresh();}else if(data.status==='pending'){setResult('录音已提交，结果仍在处理中，请稍后查询。');}else{setResult('评测未成功，录音已保留，不计作答错。可重新提交。');submission.current=null;}}catch(e){onError(errorText(e));}finally{setBusy(false);}}
 return <div className="live-reading"><aside><h2>{labels[round.stage]}</h2><p>{items.filter(i=>i.best_score!==null&&Number(i.best_score)>=80).length}/{items.length} 已通过</p>{items.map((q,index)=><button className="live-question" key={q.id} disabled={busy||recording||(first>=0&&index>first)} aria-current={index===selected?'step':undefined} onClick={()=>{setSelected(index);setBlob(null);submission.current=null;setResult('');}}><span>{index+1}. {q.text}</span><small>{q.best_score===null?'未作答':`${q.best_score} / 100`}</small></button>)}</aside><section className="live-card"><p>每题 80 分通过</p><h1>{item?.text}</h1>{round.status!=='passed'&&<><button disabled={busy} onClick={()=>recording?recorder.current?.stop():void start()}>{recording?'结束录音':'开始录音'}</button><label className="live-upload">或选择录音<input type="file" accept="audio/*" disabled={recording||busy} onChange={e=>{const value=e.target.files?.[0];if(value){setBlob(value);submission.current=null;setResult('');}}}/></label>{url&&<audio controls src={url}/>}<button disabled={!blob||busy||recording} onClick={upload}>{busy?'正在评测…':'提交评测'}</button></>}{result&&<p role="status">{result}</p>}{round.status==='passed'&&<h2>本关已通过 ✓</h2>}</section></div>;
}

function Grammar({round,onRound,onError}:{round:Round;onRound:(r:Round)=>void;onError:(t:string)=>void}){
 const [choice,setChoice]=useState<number|null>(null),[busy,setBusy]=useState(false),[feedback,setFeedback]=useState(''),[next,setNext]=useState<Round|null>(null);
 const submission=useRef<string|null>(null),elapsed=useRef(0),since=useRef(performance.now());
 const q=round.question;
 useEffect(()=>{elapsed.current=0;since.current=performance.now();const visibility=()=>{const now=performance.now();if(document.hidden)elapsed.current+=now-since.current;else since.current=now;};document.addEventListener('visibilitychange',visibility);return()=>document.removeEventListener('visibilitychange',visibility);},[q?.id]);
 async function submit(){if(choice===null||!q)return;setBusy(true);onError('');submission.current??=crypto.randomUUID();try{const data=await liveApi<{correct:boolean;round:Round}>(`/grammar/rounds/${round.id}/answers`,{question_id:q.id,selected_option:choice,client_submission_id:submission.current,active_duration_ms:Math.min(7200000,Math.round(elapsed.current+(document.hidden?0:performance.now()-since.current)))});setFeedback(data.correct?'回答正确':'回答错误');setNext(data.round);}catch(e){onError(errorText(e));}finally{setBusy(false);}}
 return <section className="live-card"><p>语法考核 · {round.answers?.length||0}/{round.total} 已答</p>{round.status==='in_progress'&&q?<><h1>{q.prompt}</h1>{[q.option_a,q.option_b].map((option,index)=><button className="live-option" key={index} disabled={busy||!!next} aria-pressed={choice===index} onClick={()=>{setChoice(index);submission.current=null;}}>{String.fromCharCode(65+index)}. {option}</button>)}{feedback&&<p role="status">{feedback}</p>}{next?<button onClick={()=>{onRound(next);setNext(null);setChoice(null);setFeedback('');submission.current=null;}}>继续 →</button>:<button disabled={choice===null||busy} onClick={submit}>{busy?'正在保存…':'提交答案'}</button>}</>:<><h1>{round.status==='passed'?'第三关通过！':'本轮未通过'}</h1><p>答对 {round.answers?.filter(a=>a.correct).length} / {round.total} 题</p><p>{round.status==='passed'?'请在 My Page 的 Book My Training 中预约 FT Signature Flow；预约结果以教师端为准。':'重新进入本关会打乱顺序；未完成的轮次会保留进度。'}</p></>}</section>;
}

function App(){
 const [teacher,setTeacher]=useState<Teacher|null>(null),[enrollment,setEnrollment]=useState<Enrollment|null>(null),[round,setRound]=useState<Round|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[passed,setPassed]=useState<Stage[]>([]),[feedback,setFeedback]=useState('');
 async function load(){setLoading(true);try{const me=await liveApi<Teacher>('/me');const list=await liveApi<Enrollment[]>('/enrollments');setTeacher(me);setEnrollment(list[0]||null);setError(list.length?'':'当前账号尚未分配培训，请联系培训负责人。');if(list[0])await progress(list[0].id);}catch(e){if(e instanceof LiveApiError&&e.status===401){setTeacher(null);setError('');}else setError(errorText(e));}finally{setLoading(false);}}
 async function progress(id:string){const value=await liveApi<{rounds:{stage:Stage;status:string}[]}>(`/enrollments/${id}/progress`);setPassed([...new Set(value.rounds.filter(r=>r.status==='passed').map(r=>r.stage))]);}
 useEffect(()=>{void load();},[]);
 async function enter(stage:Stage){if(!enrollment)return;setBusy(true);setError('');try{const r=await liveApi<Round>(`/enrollments/${enrollment.id}/stages/${stage}/round`,{});setRound(r);await progress(enrollment.id);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function logout(){try{await liveApi('/auth/logout',{});setTeacher(null);setEnrollment(null);setRound(null);setPassed([]);}catch(e){setError(errorText(e));}}
 async function sendFeedback(){if(!enrollment||!feedback.trim())return;setBusy(true);try{await liveApi('/feedback',{enrollment_id:enrollment.id,page_path:location.pathname,content:feedback,client_submission_id:crypto.randomUUID()});setFeedback('');setError('反馈已保存。');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 if(loading)return <main className="live-card"><p>正在读取培训…</p></main>;
 if(!teacher)return <><Login onLogin={()=>void load()}/>{error&&<p className="live-banner" role="alert">{error}<button onClick={()=>void load()}>重试连接</button></p>}</>;
 return <div className="live-app"><header className="fl-header"><a className="fl-brand" href="/">51Talk<span>FT 教师培训</span></a><span>{teacher.external_id||teacher.email}{teacher.is_test_account?' · 测试账号':''}</span><button onClick={logout}>退出登录</button></header><main><nav className="live-stages">{stages.map((stage,index)=><button key={stage} disabled={busy||!enrollment||(index>0&&!passed.includes(stages[index-1]))} onClick={()=>void enter(stage)}>{index+1}. {labels[stage]} {passed.includes(stage)?'✓':''}</button>)}</nav>{error&&<p role="alert" className="live-banner">{error}</p>}{!round?<section className="live-card"><h1>准备好，迎接你的课堂。</h1><p>成绩按账号保存，刷新或换设备后可继续本轮题目。</p><button disabled={!enrollment||busy} onClick={()=>void enter('word')}>开始培训 →</button></section>:round.stage==='grammar'?<Grammar key={round.id} round={round} onError={setError} onRound={r=>{setRound(r);if(enrollment)void progress(enrollment.id);}}/>:<Reading key={round.id} round={round} onError={setError} onRefresh={()=>enter(round.stage)}/>}<details className="live-card"><summary>反馈体验问题</summary><label>描述问题<textarea value={feedback} maxLength={5000} onChange={e=>setFeedback(e.target.value)}/></label><button disabled={busy||!feedback.trim()} onClick={sendFeedback}>提交反馈</button></details></main></div>;
}
createRoot(document.getElementById('root')!).render(<App/>);
